### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Nothing4You** [stacybrock/google-tracking-b-gone#1]
Hey there,
do you plan on still maintaining this?
Appearently google has changed some things that prevent this from working.
Tested with Firefox 52.

**Comment by stacybrock** [comment]
I am aware of the issue and am investigating a fix. Thanks!

**Comment by stacybrock** [comment]
Fixed in version 2.4: https://github.com/stacybrock/google-tracking-b-gone/commit/f55f890703eb3ec234aa43d998e66287eab94db4
