### ISSUE TITLE
Script no longer works, jumbled google URLs return

### ISSUE THREAD

**Issue by re11ding** [stacybrock/google-tracking-b-gone#7]
Hey, just giving a small update where it seems that the script no longer functions, likely due to a google page update as they're always doing! Figured I'd give the heads up to see if you could resolve it. Not much else to say here, specifically using google.com and it still occurs with all other addons disabled. So it's no conflict by any means causing the issue.

**Comment by re11ding** [comment]
More information! It seems this, like with many google page updates, is being rolled out slowly. What has happened is that there is no longer an event listener on <a> elements, meaning the script in turn isn't doing anything. I cannot currently find how it's changing the URLs in the new instance.

**Comment by re11ding** [comment]
Okay, so as with most google updates, it's being rolled out to specific PCs slowly. Unfortunately I have no way to provide a means to test without you being applied to one of the updates, but I can tell you exactly what changed. There's no longer an event listener on `<a>`. In fact, I have no idea where the event listeners moved to. They have to exist somewhere to work the way they do, no?

**Comment by re11ding** [comment]
`function() {
    function b(c) {
        var a;
        a: {
            for (a = c.target; a && a != document.documentElement; a = a.parentElement)
                if ("A" == a.tagName && "1" == a.getAttribute("data-jsarwt")) break a;a = null
        }
        a && window.jsarwt(a, null, c);
        return !0
    };
    window.document.documentElement.addEventListener("mousedown", b, !0);
    window.document.documentElement.addEventListener("touchstart", b, !0);
}`

This, which is in the head, would be the cause of the problem.

**Comment by re11ding** [comment]
Since the event is in the head now, `stopPropagation()` cannot simply be used as it would stop all events within the head, which the site needs to run well. There's no way (from what I can tell) that userscript can get around this. I'm not very experienced with userscript or javascript, but at least know my way around programming. If I find a way to provide a page for you to test the new method, I'll definitely do so. But the one I'm experiencing is tied to my account, so I don't feel comfortable sharing the Complete HTML of that page.

**Comment by re11ding** [comment]
Because I was so persistent, I _did_ make a working script. But, it's very hacky and I'm not a fan of it. I would still like it when this update is pushed everywhere that you make a less crux-like script with your expertise! The reason this is considered "hacky" is because it absolutely requires that in Tampermonkey's advanced settings (Make sure config mode is set to "Advanced") that inject mode all the way at the bottom **must** be set to "Instant" instead of "Default". This is because it's basically rewriting the embedded script in the head before the page loads, which it can't do if it doesn't have instant injection as the page already begins running the script before the modifications are finished. This was the only way I could think to approach this. Here's the script at the very least both for proper reference and for any bypassers who are looking for an updated script to have a temporary solution until something more solid comes out. 
```
if (document.head) {
  throw new Error('Head already exists - make sure to enable instant script injection');
}
new MutationObserver((_, observer) => {
  const googleHeadScript = document.querySelector('script[nonce*="=="]');
  if (googleHeadScript) {
    var temp = googleHeadScript.innerHTML;
    temp = temp.replace(/if\("A"==a\.tagName&&"1"==a\.getAttribute\("data-jsarwt"\)\)/m, "if(\"B\"==a.tagName&&\"1\"==a.getAttribute(\"data-jsarwt\"))");
    temp = temp.replace(/\r\n/g, "\n");
    googleHeadScript.innerHTML = temp;
    observer.disconnect();
  }
})
  .observe(document.documentElement, { childList: true, subtree: true });
```

**Comment by stacybrock** [comment]
Thank you for the detailed bug report! I'll look into it as soon as I get a chance, I'm pretty slammed at the moment with other business.

I have to admit that I switched to using DuckDuckGo as my daily-driver search engine, so I appreciate the notice as I probably wouldn't have realized this script was broken otherwise!

**Comment by re11ding** [comment]
No worries, I appreciate you trying to work on it despite making the switch! As I said, the update isn't out for all, given how google pushes updates. But as I mentioned in [this post](https://github.com/stacybrock/google-tracking-b-gone/issues/7#issuecomment-792050883), if this line of code (it should be on line 21 in most cases, haven't found one where it isn't.) exists in the header when using the debugger, then you should have it! It does not apply in Chrome for obvious reasons, as they have the tracking built in and don't need it on the site.

**Comment by re11ding** [comment]
[Google Search Complete HTML.zip](https://github.com/stacybrock/google-tracking-b-gone/files/6158045/Google.Search.Complete.HTML.zip)
Finally! I got it through an incognito window. This should help you tremendously! Please, keep me updated on how progress goes. If there's anything I can do to help despite my limited knowledge, I'll gladly do my best!

**Comment by re11ding** [comment]
Hey! Just checking if any progress at all has been made since it's been a few months. Would appreciate hearing back!

**Comment by stacybrock** [comment]
I do have an update, but it's not what you want to hear: as I no longer use Google as my primary search engine, I don't really have the time or motivation to continue updating this script. It's had a good run... over a decade of use!

I would suggest you look into another extension, something like ClearURLs (https://gitlab.com/KevinRoebert/ClearUrls) which is actively maintained and strips click tracking from _hundreds_ of websites, not just Google.
